theme: jekyll-theme-slate
# title: Americans in Germany
title: American Culture Club
# description: the club for Americans at heart
description: "the club for Americans at heart, all over Germany"
# subdescription: "all over Germany"
