theme: jekyll-theme-slate
# title: Americans in Germany
title: American Culture Club
# description: the culture club for Americans at heart
description: "the culture club for Americans at heart: in Germany and beyond!"
